### ISSUE TITLE
How to get a "rad_boost" file?

### ISSUE THREAD

**Issue by leosang** [utkarsh2254/high-resolution-image-denoising#2]
I want to use my image like "xx.png" to train my own model, while the paths of images in the code is like     " train_string_set2=['/AKASHDP_DATA3/ankur/train/A1-NAO-25-FEB-2016-103342-R3-1_b1.rad_boost']", I don't know what is a "rad_boost" file and how to get it.

**Comment by utkarshojha** [comment]
Hi sorry for such late reply. Well the directory which I  have specified is actually the directory in the computer on which I worked during my internship. So basically you can change it to your directory containing images. Just ensure that you convert your images into numpy arrays before proceeding forward. You can read .png images using numpy.asarray() function
